# Generated by Django 4.2.7 on 2025-01-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_send_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_user',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='send_user',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='send_user',
            name='mobile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
