# Generated by Django 4.2.7 on 2024-12-05 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispatch_type', models.TextField(blank=True, null=True)),
                ('inward_no', models.TextField(blank=True, null=True)),
                ('outward_no', models.TextField(blank=True, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('from_field', models.TextField(blank=True, db_column='from', null=True)),
                ('to', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('send_user', models.TextField(blank=True, null=True)),
                ('branch', models.TextField(blank=True, null=True)),
                ('stakeholders', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_wf', to='Masters.status_master')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow',
            },
        ),
        migrations.CreateModel(
            name='workflow_document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_doc', to='Workflow.workflow')),
            ],
            options={
                'db_table': 'workflow_document',
            },
        ),
    ]
