# Generated by Django 4.2.7 on 2024-12-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='inward_no',
            new_name='dispatch_no',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='outward_no',
        ),
    ]
