# Generated by Django 4.2.7 on 2024-12-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0002_rename_inward_no_workflow_dispatch_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_document',
            name='workflow',
        ),
        migrations.AddField(
            model_name='workflow_document',
            name='dispatch_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
